name: Build and push chef-inspec.Dockerfile changes to Artifact Registry.

env:
  INSPEC_VERSION: "4.26.13"
  GCLOUD_PYTHON3_VERSION: "v"

on:
  push:
    branches:
      - main
    paths:
      - docker/chef-inspec.Dockerfile
      - .github/workflows/chef-inspec.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2.1.4"

      - name: Check out the repo
        uses: actions/checkout@v4.2.2

      - id: "auth"
        uses: "google-github-actions/auth@v2.1.8"
        with:
          workload_identity_provider: "projects/43765002375/locations/global/workloadIdentityPools/github-pool/providers/github-pool-provider" # pragma: allowlist secret
          service_account: "github@bibt-containers.iam.gserviceaccount.com"

      - name: "Use gcloud CLI"
        run: "gcloud auth configure-docker"

      - name: Build and push
        uses: docker/build-push-action@v6.15.0
        with:
          push: true
          context: docker
          file: docker/chef-inspec.Dockerfile
          build-args: |
            INSPEC_VERSION=${{ env.INSPEC_VER }}
            GCLOUD_PYTHON3_VERSION=${{ env.GCLOUD_PYTHON3_VER }}
          tags: |
            us-docker.pkg.dev/bibt-containers/chef-inspec:v${{ env.INSPEC_VER }}-${{ env.GCLOUD_PYTHON3_VER }}
            us-docker.pkg.dev/bibt-containers/chef-inspec:latest
