name: Build and push gce-tcp-scanner/Dockerfile changes to Artifact Registry.

on:
  push:
    branches:
      - main
    paths:
      - docker/gce-tcp-scanner/

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2.1.4"

      - name: Check out the repo
        uses: actions/checkout@v4.2.2

      - id: "auth"
        uses: "google-github-actions/auth@v2.1.8"
        with:
          workload_identity_provider: "projects/43765002375/locations/global/workloadIdentityPools/github-pool/providers/github-pool-provider" # pragma: allowlist secret
          service_account: "github@bibt-containers.iam.gserviceaccount.com"

      - name: "Use gcloud CLI"
        run: "gcloud auth configure-docker us-docker.pkg.dev --quiet"

      - name: Set up image tag
        id: tags
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "sha_tag=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6.15.0
        with:
          push: true
          context: docker/gce-tcp-scanner
          file: docker/gce-tcp-scanner/Dockerfile
          tags: |
            us-docker.pkg.dev/bibt-containers/docker/gce-tcp-scanner:${{ steps.tags.outputs.sha_tag }}
            us-docker.pkg.dev/bibt-containers/docker/gce-tcp-scanner:latest
