name: Build and push masscan.Dockerfile changes to Artifact Registry.

env:
  IMAGE_TAG: "1.0.0"
  GCLOUD_SDK_VERSION: "517.0.0"
  MASSCAN_COMMIT_HASH: "a31feaf5c943fc517752e23423ea130a92f0d473" # pragma: allowlist secret
  WGET_VERSION: "1.21.3-1+deb12u1"
  LIBPCAP_VERSION: "1.10.3-1"

on:
  push:
    branches:
      - main
    paths:
      - docker/masscan.Dockerfile
      - .github/workflows/masscan.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2.1.4"

      - name: Check out the repo
        uses: actions/checkout@v4.2.2

      - id: "auth"
        uses: "google-github-actions/auth@v2.1.8"
        with:
          workload_identity_provider: "projects/43765002375/locations/global/workloadIdentityPools/github-pool/providers/github-pool-provider" # pragma: allowlist secret
          service_account: "github@bibt-containers.iam.gserviceaccount.com"

      - name: "Use gcloud CLI"
        run: "gcloud auth configure-docker us-docker.pkg.dev --quiet"

      - name: Build and push
        uses: docker/build-push-action@v6.15.0
        with:
          push: true
          context: docker
          file: docker/masscan.Dockerfile
          build-args: |
            GCLOUD_SDK_VERSION=${{ env.GCLOUD_SDK_VERSION }}
            MASSCAN_COMMIT_HASH=${{ env.MASSCAN_COMMIT_HASH }}
            WGET_VERSION=${{ env.WGET_VERSION }}
            LIBPCAP_VERSION=${{ env.LIBPCAP_VERSION }}
          tags: |
            us-docker.pkg.dev/bibt-containers/docker/masscan:v${{ env.IMAGE_TAG }}
            us-docker.pkg.dev/bibt-containers/docker/masscan:latest
